cors:
  originPatterns: http://localhost:8080, http://localhost:3000
file:
  upload-dir: D:/teste/kotlin/uploads
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_kotlin?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    - /api/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
